---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest
  tags:
    - sonarr
    - arr

- name: Private Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
    internal: true
    labels:
      arr: "true"
  tags:
    - sonarr
    - arr

- name: Create Docker paths
  file:
    path: "{{ docker_sonarr_storage }}{{ item }}"
    state: directory
  with_items:
    - config
  tags:
    - sonarr
    - arr

- name: ðŸ›‘ Stop Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: "lscr.io/linuxserver/sonarr:{{ sonarr_version }}"
    state: stopped
  tags:
    - sonarr
    - arr

- name: ðŸ”¥ Remove Sonarr container
  community.docker.docker_container:
    name: sonarr
    state: absent
  tags:
    - sonarr
    - arr

- name: ðŸ“º Create NFS mount TV
  community.docker.docker_volume:
    name: nfs-tv
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_tv_mount.type }}"
      o: "{{ vault_arr_tv_mount.opts }}"
      device: "{{ vault_arr_tv_mount.device }}"
  tags:
    - sonarr
    - arr

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_downloads_mount.type }}"
      o: "{{ vault_arr_downloads_mount.opts }}"
      device: "{{ vault_arr_downloads_mount.device }}"
  tags:
    - sonarr
    - arr

- name: Recreate Sonarr container
  community.docker.docker_container:
    name: "{{ sonarr_app_name }}"
    image: "lscr.io/linuxserver/sonarr:{{ sonarr_version }}"
    state: started
    restart_policy: "{{ docker_restart_condition }}"
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8989'
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - arr-downloads:/downloads
      - "nfs-tv:/tv"
      - "{{ docker_sonarr_storage }}/config:/config"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: Host(`{{ sonarr_app_name }}.{{ traefik_domain }}`)
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
        aliases:
          - sonarr.mcharryville.space
          - sonarr.arr.mcharryville.space
          - sonarr
      - name: "{{ traefik_proxy_network }}"
        aliases:
          - sonarr.mcharryville.space
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - sonarr
    - arr