---
# Adding my own monitoring software in.
# @TODO: Fully add in this role
roles:
  # - name: geerlingguy.repo-epel
  #   version: "3.1.1"
  # - name: geerlingguy.ntp
  - name: geerlingguy.docker
    version: "7.0.1"
  - name: geerlingguy.pip
  - name: artis3n.tailscale
  - name: findarato.docker-semaphore
    src: https://github.com/Findarato/docker-semaphore.git

collections:
  - name: community.general
  - name: community.docker
    version: "4.8.6"

...