---
- name: "Install epel for extra packages  {{ ansible_os_family }}"
  package:
    name: epel-release
    state: present

# - name: "Install python bindings for SE Linux  {{ ansible_os_family }}"
#   yum:
#     name: [ "libselinux-python", "libsemanage-python", "python-pip" ]
#     state: present
