---

docker_libreNMS_influxdb: true
docker_libreNMS_influxdb_ip: tarvalon.wheel
docker_libreNMS_influxdb_port: 8086
docker_libreNMS_influxdb_username: admin
docker_libreNMS_influxdb_password: admin
docker_libreNMS_database_name: librenms

# User
local_user: joe
local_user_passwordless_sudo: false

# Docker Setup
docker_users:
  - joe
  - it

ansible_dns_host: 10.1.1.10