---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest
  tags:
    - radarr
    - arr

- name: Private Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
    internal: true
    labels:
      arr: "true"
  tags:
    - radarr
    - arr

- name: Create Docker paths
  file:
    path: "{{ docker_radarr_storage }}{{ item }}"
    state: directory
  with_items:
    - config
  tags:
    - radarr
    - arr

- name: ðŸ›‘ Stop Radarr container
  community.docker.docker_container:
    name: radarr
    image: "lscr.io/linuxserver/radarr:{{ radarr_version }}"
    state: stopped
  tags:
    - radarr
    - arr

- name: ðŸ”¥ Remove Radarr container
  community.docker.docker_container:
    name: radarr
    state: absent
  tags:
    - radarr
    - arr

- name: ðŸŽ¥ Create NFS mount movies
  community.docker.docker_volume:
    name: nfs-movies
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_movies_mount.type }}"
      o: "{{ vault_arr_movies_mount.opts }}"
      device: "{{ vault_arr_movies_mount.device }}"
  tags:
    - radarr
    - arr

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_downloads_mount.type }}"
      o: "{{ vault_arr_downloads_mount.opts }}"
      device: "{{ vault_arr_downloads_mount.device }}"
  tags:
    - radarr
    - arr

- name: Recreate Radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:{{ radarr_version }}
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    # exposed_ports:
    #   - '7878'
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - arr-downloads:/downloads
      - "nfs-movies:/movies"
      - "{{ docker_radarr_storage }}/config:/config"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
        aliases:
          - radarr.mcharryville.space
          - radarr.arr.mcharryville.space
          - radarr
      - name: "{{ traefik_proxy_network }}"
        aliases:
          - radarr.mcharryville.space
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - radarr
    - arr