---
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{docker_proxy_storage}}/{{ item }}"
    state: directory
    mode: "0775"
    group: "1000"
    owner: "1000"
  with_items:
    - le/config

- name: Create SWAG
  community.docker.docker_container:
    name: swag
    image: lscr.io/linuxserver/swag:latest
    state: started
    restart_policy: unless-stopped
    recreate: true
    pull: true
    ports:
      - "80:80/tcp"
      - "81:81/tcp"
      - "443:443/tcp"
    volumes:
      - "{{docker_proxy_storage}}/le/config:/config"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      URL: "mcharryville.space"
      SUBDOMAINS: "wildcard"
      DNSPLUGIN: "cloudflare"
      VALIDATION: "dns"
      EMAIL: "findarato@gmail.com"
      STAGING: "false"
      EXTRA_DOMAINS: "*.wled.mcharryville.space"

- name: Wait for container to start
  ansible.builtin.wait_for:
    path: "{{docker_proxy_storage}}/le/config/dns-conf/"
    state: present

# - name: Copy in custom configs Digital Ocean
#   template:
#     src: digitalocean.ini.j2
#     dest: "{{docker_proxy_storage}}/le/config/dns-conf/digitalocean.ini"
#   notify:
#     - Restart SWAG

- name: Copy in custom configs Cloudflare
  template:
    src: cloudflare.ini.j2
    dest: "{{docker_proxy_storage}}/le/config/dns-conf/cloudflare.ini"
  notify:
    - Restart SWAG